const collectionActionTypes = {
    FETCH_COLLECTION_DATA: 'FETCH_COLLECTION_DATA',
    TOGGLE_ITEM_FAVOURITE: 'TOGGLE_ITEM_FAVOURITE',
    UPDATE_FAVOURITED_ITEMS: 'UPDATE_FAVOURITED_ITEMS',
    UPDATE_FAVOURITE:'UPDATE_FAVOURITE'
}

export default collectionActionTypes