export const pageCountTypes = {
  INCREASE_PAGE_COUNT: "INCREASE_PAGE_COUNT",
  DECREASE_PAGE_COUNT: "DECREASE_PAGE_COUNT",
  GOTO_PAGE_COUNT: "GOTO_PAGE_COUNT",
  INCREASE_PAGE_LIST: "INCREASE_PAGE_LIST",
  DECREASE_PAGE_LIST: "DECREASE_PAGE_LIST",
};
